services:
  backend:
    build: ./backend

    command: uvicorn main:app --reload --proxy-headers --host 0.0.0.0 --port 8000

    volumes:
      - ./backend:/usr/src/backend

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`localhost`)"

    networks:
      - appnet

  web:
    image: traefik:latest

    ports:
      - 80:80
      - 8080:8080

    volumes:
      - "./traefik/api.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    depends_on:
      - backend

    networks:
      - appnet

networks:
  appnet:
    driver: bridge